### ISSUE TITLE
Why topo_path_search is empty?

### ISSUE THREAD

**Issue by zhanghao328** [ZJU-FAST-Lab/GPA-Teleoperation#2]

**Comment by Bottle101** [comment]
Did you started the python script and send gaze data? Could you please provide more detailed description or snapshots?

**Comment by zhanghao328** [comment]
https://github.com/ZJU-FAST-Lab/GPA-Teleoperation/blob/master/src/assisted_planner/src/planner/topo_path_search
I mean the directory is empty, there is no cpp files.
Do i need to download it from other branch?
thanks a lot

**Comment by Bottle101** [comment]
Thanks for pointing it out, already fixed, please check out the latest version.
