### ISSUE TITLE
how to run the code like sim_1.gif

### ISSUE THREAD

**Issue by Sunnybigboy** [ZJU-FAST-Lab/GPA-Teleoperation#4]
hello  can you tell me how to run the code like "THE sim_1.gif"

thank you very much

**Comment by Bottle101** [comment]
Do you have any problems when following our readme?

**Comment by Bottle101** [comment]
Oh sorry that is from another project: https://github.com/ZJU-FAST-Lab/Auto-Filmer

I will fix this issue.

**Comment by Sunnybigboy** [comment]
thanks a lot ，When I run this code, it shows gui. py and the process is dead. What is the reason for this and how can I run the code to achieve the effect of sim.1? Thank you



在 2023-12-08 01:09:07，"Botao He" ***@***.***> 写道：

Closed #4 as completed.

**Comment by Bottle101** [comment]
Hii, the reason for compatibility issue varies, could you please post your error infomation so that we can provide a more detailed suggestions for you? Here are two possible reasons: 1. we have two gui, one for OpenCV4 and another for OpenCV3, please check your OpenCV version. 2. Check whether the depth images are rendered properly by visulizing it in Rviz/rqt_image_view, if not, please follow the instructions in our readme to configure your GPU settings properly.

**Comment by Sunnybigboy** [comment]
thanks a lot ，Recently, I have read the code and paper about Visplanner in BSpline_ No code related to OE cost found in optimizeer.cpp file. May I ask if it is bspline_ Is the last function block in the optimizer.cpp file



At 2023-12-18 02:05:12, "Botao He" ***@***.***> wrote:

Hii, the reason for compatibility issue varies, could you please post your error infomation so that we can provide a more detailed suggestions for you? Here are two possible reasons: 1. we have two gui, one for OpenCV4 and another for OpenCV3, please check your OpenCV version. 2. Check whether the depth images are rendered properly by visulizing it in Rviz/rqt_image_view, if not, please follow the instructions in our readme to configure your GPU settings properly.

**Comment by wangxuexiFINR** [comment]
calcVisibilityReboundCost

**Comment by Sunnybigboy** [comment]
你好 我阅读了该论文对应的代码 在calcVisibilityReboundCost部分里找到了Eigen::Vector3d pk=lambda_k*now_pos+(1-lambda_k)*swarm_pos 和double threshold_k=dist_thread*(1-lambda)*line_norm分别对应该论文的公式3和公式4 但是代价函数是cost+=pow(threshold-dist,3)*lambda 和论文里的代价函数不一样，请问是什么原因，还有一个问题是最后一行代码visibility_grad=visibility_grad+grad_vis 是什么意思 感谢您的解答



在 2023-12-28 13:06:10，"wangxuexiFINR" ***@***.***> 写道：

calcVisibilityReboundCost

**Comment by Sunnybigboy** [comment]
你好 我看在simulator.xml文件中提示有两种地图可以使用，请问怎么更换地图 谢谢您的解答

**Comment by Bottle101** [comment]
Hi, I don't think we have an official tutorial about changing the map, while you can try to change the parameters in sim.launch-><node pkg ="map_generator" name ="random_forest" type ="random_forest" output = "screen">, let us know if it works for you.

**Comment by Sunnybigboy** [comment]
hello Can you please tell me how the entire three-dimensional simulation environment and simulated drone in the code are built? Which software or which installation packages are used to achieve this? I really hope you can tell me. Thank you very much.



At 2024-01-17 01:25:19, "Botao He" ***@***.***> wrote:

Hi, I don't think we have an official tutorial about changing the map, while you can try to change the parameters in sim.launch->, let us know if it works for you.
